#ifndef PANDUZA_H
#define PANDUZA_H
#pragma once

#include "config.h"

#define SLASH_STR "/"
#define DOTS_STR ":"

#define PANDUZA_BASE "pza"
#define PANDUZA_BENCH_NAME "default"
#define PANDUZA_ITF_IO "io"

#define PANDUZA_ATTS_INFO UTIL_CAT(PANDUZA_BASE, SLASH_STR, PANDUZA_BENCH_NAME, SLASH_STR, CONFIG_BOARD, SLASH_STR, PANDUZA_ITF_IO, "/info")

#define PANDUZA_TOPIC_IO UTIL_CAT(PANDUZA_BASE, SLASH_STR, PANDUZA_BENCH_NAME, SLASH_STR, CONFIG_BOARD, SLASH_STR, DOTS_STR, PANDUZA_ITF_IO)

#endif